/*
 * generated by Xtext
 */
package com.bichler.iec.validation
import org.eclipse.xtext.validation.Check
import com.bichler.iec.iec.FunctionDeclaration
import com.bichler.iec.iec.IecPackage

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class IecValidator extends AbstractIecValidator {

//  public static val INVALID_NAME = 'invalidName'
//
	@Check
	def checkFunctionNameForReserved(FunctionDeclaration function) {
//		if (function.name.compareTo("AD") == 0) {
//			error('ADD is a reserved keyword!', 
//					 IecPackage.Literals.FUNCTION_DECLARATION__NAME,
//					'reserved keyword')
//		}
	}
}
