/*
 * generated by Xtext
 */
package com.bichler.iec;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class IecUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return com.bichler.iec.ui.internal.IecActivator.getInstance().getInjector("com.bichler.iec.Iec");
	}

}
