/*
 * generated by Xtext
 */
package com.bichler.iec.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.model.IResourceForEditorInputFactory;
import org.eclipse.xtext.ui.editor.model.XtextDocumentProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IecUiModule extends com.bichler.iec.ui.AbstractIecUiModule {
//	@Override
//	public Class<? extends IContentProposalProvider> bindIContentProposalProvider() {
//		return IECContentProposalProvider.class;
//	}

	public IecUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
        return IECHoverProvider.class;
    }
 
    public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProviderr() {
        return IECMultiLineCommentDocumentationProvider.class;
    }
    
    public Class<? extends IResourceForEditorInputFactory> bindIResourceForEditorInputFactory() {
        return MyJavaClassPathResourceForIEditorInputFactory.class;
    }

    @Override
    public Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
        return MyNatureAddingEditorCallback.class;
    }
    
    public Class<? extends XtextDocumentProvider> bindXtextDocumentProvider() {
        return MyXtextDocumentProvider.class;
    }
    
    public Class<? extends XtextDocumentProvider> bindDocumentProvider() {
    	return MyXtextDocumentProvider.class;
    	}
}
