package com.bichler.astudio.editor.pubsub.nodes;

public enum DataSetFieldContentMask {
	UA_DATASETFIELDCONTENTMASK_NONE(0), UA_DATASETFIELDCONTENTMASK_STATUSCODE(1),
	UA_DATASETFIELDCONTENTMASK_SOURCETIMESTAMP(2), UA_DATASETFIELDCONTENTMASK_SERVERTIMESTAMP(4),
	UA_DATASETFIELDCONTENTMASK_SOURCEPICOSECONDS(8), UA_DATASETFIELDCONTENTMASK_SERVERPICOSECONDS(16),
	UA_DATASETFIELDCONTENTMASK_RAWDATA(32), __UA_DATASETFIELDCONTENTMASK_FORCE32BIT(0x7fffffff);

	private final int value;

	private DataSetFieldContentMask(int value) {
		this.value = value;
	}
}
