package com.bichler.astudio.editor.pubsub.nodes;

public enum PubSubPublishedDataSetType {
	UA_PUBSUB_DATASET_PUBLISHEDITEMS, UA_PUBSUB_DATASET_PUBLISHEDEVENTS, UA_PUBSUB_DATASET_PUBLISHEDITEMS_TEMPLATE,
	UA_PUBSUB_DATASET_PUBLISHEDEVENTS_TEMPLATE,
}
