/*
 * generated by Xtext
 */
package com.bichler.iec.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.bichler.iec.services.IecGrammarAccess;

public class IecParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private IecGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.bichler.iec.parser.antlr.internal.InternalIecParser createParser(XtextTokenStream stream) {
		return new com.bichler.iec.parser.antlr.internal.InternalIecParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public IecGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IecGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
