/*
 * generated by Xtext
 */
package com.bichler.iec;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IecRuntimeModule extends com.bichler.iec.AbstractIecRuntimeModule {

}
