/*
* generated by Xtext
*/
package com.bichler.iec;

import com.bichler.iec.IecStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class IecStandaloneSetup extends IecStandaloneSetupGenerated{

	public static void doSetup() {
		new IecStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

