# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - name: Print NSIS version
    #  run: makensis -VERSION      
    - uses: actions/checkout@v2
    - name: Step 1 - Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    
    - name: Step 2 - Set up NSIS Installer
      run: sudo apt update && sudo apt install -y nsis nsis-pluginapi    
    # - name: LS
    #  run: ls  
    - name: Step 3 - Build AutomationStudio
      run: |
        mvn clean install
    # - name: LS2
    #  run: ls /home/runner/work/BichlerTechStudio/BichlerTechStudio/releng/com.bichler.automationstudio.product/target
    - name: Step 4 - Set up Cache for Artifact
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Step 5 - Create Installer for AutomationStudio
      run: |
        makensis /home/runner/work/BichlerTechStudio/BichlerTechStudio/installer/setup.nsi
    #    ls  /home/runner/work/BichlerTechStudio/BichlerTechStudio/installer
   
    - name: Step 6.0 - Upload Installer to FTP
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ftp.bichler.tech/
        ftp_username: ftp5852803_btech
        ftp_password: btech2021
        local_source_dir: "/home/runner/work/BichlerTechStudio/BichlerTechStudio/installer/setup"
        dist_target_dir: "/latest"
        delete: "true"
        
    # - name: Step 6 - Persist Worklfow Data as Artifacts
    #  uses: actions/upload-artifact@v2
    #  with:
    #   name: AutomationStudio
    #   path: /home/runner/work/BichlerTechStudio/BichlerTechStudio/installer/AutomationStudio.exe
    #  path: /home/runner/work/BichlerTechStudio/BichlerTechStudio/releng/com.bichler.automationstudio.product/target/products/com.bichler.astudio.product.feature/win32/win32/x86_64
